import Head from "next/head";
import { useRouter } from "next/router";
import CharacterItem from "../src/components/characterItem";
import { useEffect, useState } from "react";
import LiveSearcher from "../src/components/liveSearcher";
export default function Home() {
  const router = useRouter();
  const [characterItem, setCharacterItem] = useState({});

  useEffect(() => {
    // Verifica si router.query.character tiene un valor antes de analizarlo
    if (router.query.character) {
      setCharacterItem(JSON.parse(router.query.character));
    }
  }, [router.query.character]);

  return (
    <>
      <Head>
        <title>Shipunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*customizar esto */}
      <div className="flex w-full h-screen ">
        <div
          className={`grid items-center justify-center w-full  ${
            characterItem.estado_personaje
              ? "bg-gradient-to-br  from-[#6bfaff] to-[#0c0511]"
              : "bg-gradient-to-br from-rose-700 to-[#0c0511]"
          }`}
        >
          <div className="grid justify-center w-full text-center ">
            <CharacterItem characterItem={characterItem} />
          </div>
        </div>
      </div>
    </>
  );
}
