/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import LiveSearcher from "../src/components/liveSearcher";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shipunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full h-screen overflow-auto">
        <div className="flex items-center h-full w-[70%] max-w-[2600px] m-auto">
          <div className="">
            <h1 className="text-7xl text-white mb-5 font-bold first-letter:text-[#7A0BC0] first-letter:text-9xl">
              Shipunk
            </h1>
            <p className="text-white">
              Tu lugar para encontrar a tus personajes favoritos de Cyberpunk
              edgerunners
            </p>
            <LiveSearcher />
          </div>
          <div className="max-lg:hidden">
            <img
              src="https://res.cloudinary.com/dbtzbuew2/image/upload/v1695099776/Vector_165_yodaaf.png"
              alt="logo"
              className="w-80 h-80"
            />
          </div>
        </div>
      </div>
    </>
  );
}
