/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import LiveSearcher from "../src/components/liveSearcher";
import { AiFillGithub } from "react-icons/ai";
export default function Home() {
  return (
    <>
      <Head>
        <title>Shipunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./logo.png" />
      </Head>
      <div className="flex w-full h-screen overflow-auto">
        <div className="fixed right-0 p-3 ">
          <a
            href="https://github.com/SaulLudena/shipunk"
            target="_blank"
            className="flex items-center gap-2 px-2 py-1 text-gray-900 bg-gray-300 rounded-lg"
          >
            <AiFillGithub size={35} />
          </a>
        </div>

        <div className="flex items-center h-full w-[70%] max-w-[2600px] m-auto">
          <div>
            <h1 className="text-7xl text-white mb-5 font-bold first-letter:text-[#7A0BC0] first-letter:text-9xl">
              Shipunk
            </h1>
            <p className="text-white">
              Tu lugar para encontrar a tus personajes favoritos de Cyberpunk
              edgerunners
            </p>

            <LiveSearcher />
          </div>
          <div className="max-lg:hidden">
            <img
              src="https://res.cloudinary.com/dbtzbuew2/image/upload/v1695099776/Vector_165_yodaaf.png"
              alt="logo"
              className="w-80 h-80"
            />
          </div>
        </div>
      </div>
    </>
  );
}
